server:
  #服务注册中心端口号
  port: 6380
spring:
  application:
    name: microservice-config-client
  redis:
    # Redis数据库索引(默认为0)
    database: 0
    # Redis服务器地址
    host: 192.168.199.98
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码(默认为空，我现在设置了密码为foobared)
    password: foobared
    # Redis连接超时时间（毫秒）
    timeout: 1000ms
    pool:
      jedis:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
info: 
  app: 
    name: microservice-config-client-dev
  company:
    name: microservice-config-client-company-name
logging:
  file: F:\\logs\\microservice-redis.log
  org.common.eureka.controller : error
  level:
    root: info